---
- name: search path zsh
  command: >
    which zsh
  register: which_zsh
  ignore_errors: True

- debug: msg="{{which_zsh.stdout}}"

#
# login shell settings, you will be ased user's password when system switches to zsh.
#

- name: grep shells
  shell: >
    cat /etc/shells | grep "{{which_zsh.stdout}}"
  register: grep_shells
  ignore_errors: True

- debug: msg="{{grep_shells}}"
  when: grep_shells.rc == 0

- name: append shells
  shell: >
    echo {{which_zsh.stdout}} >> /etc/shells
  become: true
  when: grep_shells.rc != 0

- name: notify please input password
  shell: >
    osascript -e 'display notification "Prease input password in terminal" with title "osx-provisioning"'

- name: change login shell
  shell: >
    chpass -s {{which_zsh.stdout}}
  register: result
  until: result.rc == 0
  retries: 3

- stat: path=~/.zsh
  register: zshdir

- name: create .zsh directory
  file: name=~/.zsh state=directory
  when: not zshdir.stat.exists

- name: create symlink
  file: src=~/dotfiles/zsh/zshrc dest=~/.zshrc state=link
