---
- name: search path fish
  command: >
    which fish
  register: which_fish
  ignore_errors: True

- debug: msg="{{which_fish.stdout_lines}}"

#
# login shell settings, you will be ased user's password when system switches to fish.
#

- name: grep shells
  shell: >
    cat /etc/shells | grep "{{which_fish.stdout}}"
  register: grep_shells
  ignore_errors: True

- debug: msg="{{grep_shells}}"
  when: grep_shells.rc == 0

- name: append shells
  shell: >
    echo {{which_fish.stdout}} >> /etc/shells
  become: true
  when: grep_shells.rc != 0

- name: change login shell
  shell: >
    chpass -s {{which_fish.stdout}}
  register: result
  until: result.rc == 0
  retries: 3

- name: create symlink for fish
  file:
    src: ~/dotfiles/{{ item.src }}
    dest: ~/.config/{{ item.dest }}
    state: link
    force: yes
  with_items:
    - { src: 'fish', dest: 'fish'}
