- name: Create symlink  gitconfig/gitignore/tigrc
  file:
    src: ~/dotfiles/git/{{ item }}
    dest: ~/{{ item }}
    state: link
    force: yes
  with_items:
    - .gitignore
    - .gitignore_global
    - .tigrc
